[package]
name = "MaaBo"
version = "0.0.0"
description = "MAA GUI with Tauri & Vue3 for Mac OS & Linux"
authors = ["vclass"]
license = "AGPL-3.0"
repository = ""
edition = "2021"
rust-version = "1.81.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.1", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.0.2", features = ["tray-icon"] }
tauri-plugin-log = "2.0.0-rc"
tauri-plugin-clipboard-manager = "2.0.1"
tauri-plugin-shell = "2"
