/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutMaaBo: typeof import('./src/components/AboutMaaBo.vue')['default']
    AwardSetting: typeof import('./src/components/OneKey/AwardSetting.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FightSetting: typeof import('./src/components/OneKey/FightSetting.vue')['default']
    InfrastSetting: typeof import('./src/components/OneKey/InfrastSetting.vue')['default']
    MaaCliConfig: typeof import('./src/components/MaaCliConfig.vue')['default']
    MaaCopilot: typeof import('./src/components/MaaCopilot.vue')['default']
    MaaCoreConfig: typeof import('./src/components/MaaCoreConfig.vue')['default']
    MaaOneKey: typeof import('./src/components/MaaOneKey.vue')['default']
    MallSetting: typeof import('./src/components/OneKey/MallSetting.vue')['default']
    NaviLayout: typeof import('./src/components/layout/NaviLayout.vue')['default']
    ReclamationSetting: typeof import('./src/components/OneKey/ReclamationSetting.vue')['default']
    RecruitSetting: typeof import('./src/components/OneKey/RecruitSetting.vue')['default']
    RoguelikeSetting: typeof import('./src/components/OneKey/RoguelikeSetting.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StartUpSetting: typeof import('./src/components/OneKey/StartUpSetting.vue')['default']
  }
}
