name: "publish"

on:
  push:
    tags:
      - "*"

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      RELEASE_UPLOAD_ID: ${{ steps.create_release.outputs.id }}

    steps:
      - uses: actions/checkout@v4
      - name: Get version
        id: get_release_version
        shell: bash
        run: |
          echo "using version tag ${GITHUB_REF:10}"
          echo "VERSION=${GITHUB_REF:10}" >> $GITHUB_OUTPUT
      - name: Release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: "See the assets to download this version and install."
          name: "MaaBo v${{ steps.get_release_version.outputs.VERSION }}"
          tag_name: "${{ steps.get_release_version.outputs.VERSION }}"

  publish-tauri:
    needs: create-release
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            args: "--target aarch64-apple-darwin"
          - platform: "macos-latest"
            args: "--target x86_64-apple-darwin"
          - platform: "ubuntu-20.04" # for Tauri v1 you could replace this with ubuntu-20.04.
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Get version
        id: get_build_version
        shell: bash
        run: |
          echo "using version tag ${GITHUB_REF:10}"
          echo "VERSION=${GITHUB_REF:10}" >> $GITHUB_OUTPUT

      - name: Set app version
        uses: MathieuSoysal/replace-string-in-file@v1.1.0
        with:
          file: src-tauri/Cargo.toml
          old-string: version = "0.0.0"
          new-string: version = "${{ steps.get_build_version.outputs.VERSION }}"

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend dependencies
        run: npm install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__
          releaseName: "MaaBo v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}
          releaseId: ${{ needs.create-release.outputs.id }}